//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMall.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_DETAIL
    {
        public ITEM_DETAIL()
        {
            this.SEARCHED_ITEM = new HashSet<SEARCHED_ITEM>();
        }
    
        public long Item_Id { get; set; }
        public string Item_Name { get; set; }
        public string Item_Description { get; set; }
        public int Item_Type_Id { get; set; }
        public int Item_Category_Id { get; set; }
        public int Location_Id { get; set; }
        public string Uploaded_Image_Url { get; set; }
        public System.DateTime Time_Uploaded { get; set; }
        public Nullable<int> Number_Of_Item { get; set; }
        public long Added_By { get; set; }
        public decimal Price { get; set; }
    
        public virtual ITEM_CATEGORY ITEM_CATEGORY { get; set; }
        public virtual ITEM_TYPE ITEM_TYPE { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        public virtual ICollection<SEARCHED_ITEM> SEARCHED_ITEM { get; set; }
        public virtual USER USER { get; set; }
    }
}
