//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMall.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public LOCATION()
        {
            this.ITEM_DETAIL = new HashSet<ITEM_DETAIL>();
        }
    
        public int Location_Id { get; set; }
        public string Location_Name { get; set; }
        public string Location_Description { get; set; }
    
        public virtual ICollection<ITEM_DETAIL> ITEM_DETAIL { get; set; }
    }
}
