//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMall.Model.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class School_MallEntities : DbContext
    {
        public School_MallEntities()
            : base("name=School_MallEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ITEM_CATEGORY> ITEM_CATEGORY { get; set; }
        public virtual DbSet<ITEM_DETAIL> ITEM_DETAIL { get; set; }
        public virtual DbSet<ITEM_TYPE> ITEM_TYPE { get; set; }
        public virtual DbSet<LOCATION> LOCATION { get; set; }
        public virtual DbSet<PERSON> PERSON { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<SEARCH_RESULT> SEARCH_RESULT { get; set; }
        public virtual DbSet<SEARCHED_ITEM> SEARCHED_ITEM { get; set; }
        public virtual DbSet<SECURITY_QUESTION> SECURITY_QUESTION { get; set; }
        public virtual DbSet<SEX> SEX { get; set; }
        public virtual DbSet<USER> USER { get; set; }
    }
}
