//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMall.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEARCHED_ITEM
    {
        public long Searched_Item_Id { get; set; }
        public long Item_Id { get; set; }
        public Nullable<long> Person_Id { get; set; }
        public System.DateTime Date_Searched { get; set; }
        public int Search_Result_Id { get; set; }
    
        public virtual ITEM_DETAIL ITEM_DETAIL { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual SEARCH_RESULT SEARCH_RESULT { get; set; }
    }
}
