//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMall.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.ITEM_DETAIL = new HashSet<ITEM_DETAIL>();
        }
    
        public long User_Id { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public string Image_Url { get; set; }
        public int Security_Question_Id { get; set; }
        public string Security_Answer { get; set; }
        public Nullable<long> Person_Id { get; set; }
        public System.DateTime Last_Login_Date { get; set; }
    
        public virtual ICollection<ITEM_DETAIL> ITEM_DETAIL { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual ROLE ROLE { get; set; }
        public virtual SECURITY_QUESTION SECURITY_QUESTION { get; set; }
    }
}
